In [1]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import solve_ivp
import pandas as pd

In [17]:
p = {
    'kks_1':  0.95,   #QoI
    'kkr_1':  0,   #QoI
    'kk_2':  0.95,    #SDHI
    'C50s_1': 0.02,    #QoI_azoxystrobin sensitive
    'C50s_2': 0.06,  #SDHI_fluxapyroxad sensitive
    'C50r_2': 1.4,
    'K':     1.0,    
    'beta':  0.2,    
    'mu':    0.1,    
    'rH':    0.1,   
    'rhor_1': 0,   #QoI
    'rhor_2': 0.1,     #SDHI
    'm':    3.2e-5  
}

C = np.array([0, 0.25, 0.5, 1, 2, 4]) #dose strategies, 1 represents baseline dose. (0.25-1 is selection window)

In [44]:
y0 = [0.95,     
      0.03,   
      0.0,
      0.0,
      0.0]   
t = np.linspace(0, 2000, 2000)

In [18]:
def Hills_function (C, kk, C50):
   return (kk * C / (C + C50))

C1, C2 = np.meshgrid(C, C)

e_1 = Hills_function(C1,p['kks_1'],p['C50s_1']) #QoI_azoxystrobin sensitive
es_2 = Hills_function(C2,p['kk_2'],p['C50s_2']) #SDHI_fluxapyroxad sensitive
er_2 = Hills_function(C2,p['kk_2'],p['C50r_2']) #SDHI_fluxapyroxad resistant

b_ab = p['beta']*(1-e_1)*(1-es_2)
b_Ab = p['beta']*(1-p['rhor_1'])*(1-es_2)
b_aB = p['beta']*(1-e_1)*(1-p['rhor_2'])*(1-er_2)  #SDHI resistance is quantitative, while QoI can be assumed to be qualitative
b_AB = p['beta']*(1-p['rhor_1'])*(1-p['rhor_2'])*(1-er_2)


df_doses = pd.DataFrame ({
    'QoI': C1.flatten(),
    'SDHI' : C2.flatten(),
    'b_ab': b_ab.flatten(),
    'b_Ab': b_Ab.flatten(),
    'b_aB': b_aB.flatten(),
    'b_AB': b_AB.flatten(),
    'e_1' : e_1.flatten(),
    'es_2' : es_2.flatten(),
    'er_2':er_2.flatten(),
})
print( 'fungicide mixtures and transmission rates')
df_doses

fungicide mixtures and transmission rates

,QoI,SDHI,b_ab,b_Ab,b_aB,b_AB,e_1,es_2,er_2
0,0.00,0.00,0.200000,0.200000,0.180000,0.180000,0.000000,0.000000,0.000000
1,0.25,0.00,0.024074,0.200000,0.021667,0.180000,0.879630,0.000000,0.000000
2,0.50,0.00,0.017308,0.200000,0.015577,0.180000,0.913462,0.000000,0.000000
3,1.00,0.00,0.013725,0.200000,0.012353,0.180000,0.931373,0.000000,0.000000
4,2.00,0.00,0.011881,0.200000,0.010693,0.180000,0.940594,0.000000,0.000000
5,4.00,0.00,0.010945,0.200000,0.009851,0.180000,0.945274,0.000000,0.000000
6,0.00,0.25,0.046774,0.046774,0.154091,0.154091,0.000000,0.766129,0.143939
7,0.25,0.25,0.005630,0.046774,0.018548,0.154091,0.879630,0.766129,0.143939
8,0.50,0.25,0.004048,0.046774,0.013335,0.154091,0.913462,0.766129,0.143939
9,1.00,0.25,0.003210,0.046774,0.010575,0.154091,0.931373,0.766129,0.143939
10,2.00,0.25,0.002779,0.046774,0.009154,0.154091,0.940594,0.766129,0.143939
11,4.00,0.25,0.002560,0.046774,0.008433,0.154091,0.945274,0.766129,0.143939
12,0.00,0.50,0.030357,0.030357,0.135000,0.135000,0.000000,0.848214,0.250000
13,0.25,0.50,0.003654,0.030357,0.016250,0.135000,0.879630,0.848214,0.250000
14,0.50,0.50,0.002627,0.030357,0.011683,0.135000,0.913462,0.848214,0.250000
15,1.00,0.50,0.002083,0.030357,0.009265,0.135000,0.931373,0.848214,0.250000
16,2.00,0.50,0.001803,0.030357,0.008020,0.135000,0.940594,0.848214,0.250000
17,4.00,0.50,0.001661,0.030357,0.007388,0.135000,0.945274,0.848214,0.250000
18,0.00,1.00,0.020755,0.020755,0.108750,0.108750,0.000000,0.896226,0.395833
19,0.25,1.00,0.002498,0.020755,0.013090,0.108750,0.879630,0.896226,0.395833
20,0.50,1.00,0.001796,0.020755,0.009411,0.108750,0.913462,0.896226,0.395833
21,1.00,1.00,0.001424,0.020755,0.007463,0.108750,0.931373,0.896226,0.395833
22,2.00,1.00,0.001233,0.020755,0.006460,0.108750,0.940594,0.896226,0.395833
23,4.00,1.00,0.001136,0.020755,0.005951,0.108750,0.945274,0.896226,0.395833
24,0.00,2.00,0.015534,0.015534,0.079412,0.079412,0.000000,0.922330,0.558824
25,0.25,2.00,0.001870,0.015534,0.009559,0.079412,0.879630,0.922330,0.558824
26,0.50,2.00,0.001344,0.015534,0.006872,0.079412,0.913462,0.922330,0.558824
27,1.00,2.00,0.001066,0.015534,0.005450,0.079412,0.931373,0.922330,0.558824
28,2.00,2.00,0.000923,0.015534,0.004718,0.079412,0.940594,0.922330,0.558824
29,4.00,2.00,0.000850,0.015534,0.004346,0.079412,0.945274,0.922330,0.558824
30,0.00,4.00,0.012808,0.012808,0.053333,0.053333,0.000000,0.935961,0.703704
31,0.25,4.00,0.001542,0.012808,0.006420,0.053333,0.879630,0.935961,0.703704
32,0.50,4.00,0.001108,0.012808,0.004615,0.053333,0.913462,0.935961,0.703704
33,1.00,4.00,0.000879,0.012808,0.003660,0.053333,0.931373,0.935961,0.703704
34,2.00,4.00,0.000761,0.012808,0.003168,0.053333,0.940594,0.935961,0.703704
35,4.00,4.00,0.000701,0.012808,0.002919,0.053333,0.945274,0.935961,0.703704

In [5]:
def ODEs (t,y,p,b_total):
    H, I_ab, I_Ab, I_aB, I_AB = y
    b_ab, b_Ab, b_aB, b_AB = b_total
    m = p['m']
    rH = p ['rH']
    K = p['K']
    mu = p['mu']

    dH = rH*(K - H - I_ab - I_Ab - I_aB - I_AB) - b_ab*I_ab*H - b_Ab*I_Ab*H - b_aB*I_aB*H - b_AB*I_AB*H
    dI_ab = (1-2*m)*b_ab*I_ab*H + m*b_Ab*I_Ab*H + m*b_aB*I_aB*H - mu*I_ab
    dI_Ab = m*b_ab*I_ab*H + (1-2*m)*b_Ab*I_Ab*H + m*b_AB*I_AB*H - mu*I_Ab
    dI_aB = m*b_ab*I_ab*H + (1-2*m)*b_aB*I_aB*H + m*b_AB*I_AB*H - mu*I_aB
    dI_AB = m*b_Ab*I_Ab*H + m*b_aB*I_aB*H + (1-2*m)*b_AB*I_AB*H - mu*I_AB

    return [dH, dI_ab, dI_Ab, dI_aB, dI_AB]

In [43]:
def calculate_90_threshold (sol):
    I_total = sol.y[1,:]+sol.y[2,:]+sol.y[3,:]+sol.y[4,:]
    
    proportion_I_AB = np.divide(
        sol.y[4,:],
        I_total,
        out=np.zeros_like(I_total), 
        where = (I_total) > 0)

    epidemic_threshold = 0.01 * p['K'] 
    validity = I_total > epidemic_threshold
    
    indices = np.where((proportion_I_AB >= 0.9) & validity & (sol.y[4,:] > 0))[0]

    if len(indices) > 0:
        return sol.t[indices[0]]
    else:
        return np.nan

In [42]:
results = []
def calculate_R0 (b_ab, b_Ab, b_aB, b_AB, p):
    R0_ab = b_ab * p['K'] / p['mu']
    R0_Ab = b_Ab * p['K'] / p['mu']
    R0_aB = b_aB * p['K'] / p['mu']
    R0_AB = b_AB * p['K'] / p['mu']
    return R0_ab, R0_Ab, R0_aB, R0_AB
        
    
for j in range(len(C)):
    for i in range(len(C)):
        e_1 = Hills_function(C[i], p['kks_1'], p['C50s_1'])
        es_2 = Hills_function(C[j], p['kk_2'], p['C50s_2'])
        er_2 = Hills_function(C[j], p['kk_2'], p['C50r_2'])
        b_ab = p['beta'] * (1 - e_1) * (1 - es_2)
        b_Ab = p['beta'] * (1 - p['rhor_1']) * (1 - es_2)
        b_aB = p['beta'] * (1 - e_1) * (1 - p['rhor_2']) * (1 - er_2)
        b_AB = p['beta'] * (1 - p['rhor_1']) * (1 - p['rhor_2']) * (1 - er_2)
        b_total = (b_ab, b_Ab, b_aB, b_AB)

        sol = solve_ivp(ODEs, [t[0], t[-1]], y0, t_eval=t, args=(p, b_total),
                        method='Radau',rtol=1e-10, atol=1e-12) 
        if not sol.success:
            print(f'integration failed at i={i}, j={j}')

        H_eq = sol.y[0, -1]
        I_ab_eq = sol.y[1, -1]
        I_Ab_eq = sol.y[2, -1]
        I_aB_eq = sol.y[3, -1]
        I_AB_eq = sol.y[4, -1]

        R0_ab, R0_Ab, R0_aB, R0_AB = calculate_R0(b_ab, b_Ab, b_aB, b_AB, p)
        t90 = calculate_90_threshold(sol)

        results.append({
            "QoI": C[i],
            "SDHI": C[j],
            "$H^*$": H_eq,
            "$I_{ab}^*$": I_ab_eq,
            "$I_{Ab}^*$": I_Ab_eq,
            "$I_{aB}^*$": I_aB_eq,
            "$I_{AB}^*$": I_AB_eq,
            "t90": t90,
            "$R_0{ab}": R0_ab,
            "$R_0{Ab}" : R0_Ab,
            "$R_0{aB}" : R0_aB,
            "$R_0{AB}" : R0_AB                       
        })

df_results = pd.DataFrame(results)
df_results

,QoI,SDHI,$H^*$,$I_{ab}^*$,$I_{Ab}^*$,$I_{aB}^*$,$I_{AB}^*$,t90,$R_0{ab},$R_0{Ab},$R_0{aB},$R_0{AB}
0,0.00,0.00,0.500016,1.866233e-01,6.328877e-02,5.972272e-05,2.025190e-05,NaN,2.000000,2.000000,1.800000,1.800000
1,0.25,0.00,0.500032,9.091496e-06,2.498949e-01,2.622460e-09,7.997186e-05,NaN,0.240741,2.000000,0.216667,1.800000
2,0.50,0.00,0.500032,8.754786e-06,2.498953e-01,2.524182e-09,7.997197e-05,NaN,0.173077,2.000000,0.155769,1.800000
3,1.00,0.00,0.500032,8.586431e-06,2.498954e-01,2.475073e-09,7.997202e-05,NaN,0.137255,2.000000,0.123529,1.800000
4,2.00,0.00,0.500032,8.502253e-06,2.498955e-01,2.450526e-09,7.997205e-05,NaN,0.118812,2.000000,0.106931,1.800000
5,4.00,0.00,0.500032,8.460164e-06,2.498956e-01,2.438254e-09,7.997207e-05,NaN,0.109453,2.000000,0.098507,1.800000
6,0.00,0.25,0.648988,4.032006e-06,4.031895e-06,8.775010e-02,8.774768e-02,NaN,0.467742,0.467742,1.540909,1.540909
7,0.25,0.25,0.649009,1.068252e-10,8.063388e-06,6.384223e-06,1.754810e-01,31.015508,0.056302,0.467742,0.185480,1.540909
8,0.50,0.25,0.649009,9.792761e-11,8.063399e-06,6.147779e-06,1.754812e-01,31.015508,0.040478,0.467742,0.133348,1.540909
9,1.00,0.25,0.649009,9.351994e-11,8.063404e-06,6.029556e-06,1.754814e-01,30.015008,0.032100,0.467742,0.105749,1.540909
10,2.00,0.25,0.649009,9.132690e-11,8.063407e-06,5.970445e-06,1.754814e-01,30.015008,0.027787,0.467742,0.091539,1.540909
11,4.00,0.25,0.649009,9.023314e-11,8.063408e-06,5.940889e-06,1.754815e-01,30.015008,0.025598,0.467742,0.084328,1.540909
12,0.00,0.50,0.740764,2.675523e-06,2.675474e-06,6.480681e-02,6.480562e-02,NaN,0.303571,0.303571,1.350000,1.350000
13,0.25,0.50,0.740788,5.824187e-11,5.350484e-06,4.714863e-06,1.295959e-01,34.017009,0.036541,0.303571,0.162500,1.350000
14,0.50,0.50,0.740788,5.209081e-11,5.350491e-06,4.540244e-06,1.295960e-01,33.016508,0.026271,0.303571,0.116827,1.350000
15,1.00,0.50,0.740788,4.903979e-11,5.350495e-06,4.452935e-06,1.295961e-01,33.016508,0.020833,0.303571,0.092647,1.350000
16,2.00,0.50,0.740788,4.752073e-11,5.350497e-06,4.409280e-06,1.295962e-01,33.016508,0.018034,0.303571,0.080198,1.350000
17,4.00,0.50,0.740788,4.676286e-11,5.350498e-06,4.387453e-06,1.295962e-01,33.016508,0.016613,0.303571,0.073881,1.350000
18,0.00,1.00,0.919570,7.952062e-07,7.951943e-07,2.010694e-02,2.010664e-02,NaN,0.207547,0.207547,1.087500,1.087500
19,0.25,1.00,0.919599,1.570401e-11,1.589812e-06,1.462433e-06,4.019740e-02,40.020010,0.024983,0.207547,0.130903,1.087500
20,0.50,1.00,0.919599,1.383846e-11,1.589814e-06,1.408271e-06,4.019746e-02,40.020010,0.017961,0.207547,0.094111,1.087500
21,1.00,1.00,0.919599,1.291235e-11,1.589815e-06,1.381189e-06,4.019749e-02,40.020010,0.014243,0.207547,0.074632,1.087500
22,2.00,1.00,0.919599,1.245106e-11,1.589815e-06,1.367649e-06,4.019750e-02,40.020010,0.012330,0.207547,0.064604,1.087500
23,4.00,1.00,0.919599,1.222086e-11,1.589816e-06,1.360878e-06,4.019751e-02,40.020010,0.011358,0.207547,0.059515,1.087500
24,0.00,2.00,1.000000,1.945090e-21,1.945060e-21,4.889235e-17,4.889159e-17,NaN,0.155340,0.155340,0.794118,0.794118
25,0.25,2.00,1.000000,1.162208e-26,1.160061e-21,1.060830e-21,2.915869e-17,NaN,0.018698,0.155340,0.095588,0.794118
26,0.50,2.00,1.000000,1.118575e-25,1.264138e-20,1.113189e-20,3.177471e-16,NaN,0.013443,0.155340,0.068722,0.794118
27,1.00,2.00,1.000000,1.905891e-26,2.305200e-21,1.990903e-21,5.794231e-17,NaN,0.010661,0.155340,0.054498,0.794118
28,2.00,2.00,1.000000,8.710457e-26,1.091735e-20,9.336409e-21,2.744128e-16,NaN,0.009228,0.155340,0.047175,0.794118
29,4.00,2.00,1.000000,5.302439e-26,6.768310e-21,5.759539e-21,1.701247e-16,NaN,0.008501,0.155340,0.043459,0.794118
30,0.00,4.00,1.000000,2.192318e-23,2.452837e-23,6.133716e-19,6.133593e-19,NaN,0.128079,0.128079,0.533333,0.533333
31,0.25,4.00,1.000000,3.603018e-27,4.022468e-22,3.474748e-22,9.551022e-18,NaN,0.015417,0.128079,0.064198,0.533333
32,0.50,4.00,1.000000,2.065564e-27,2.428946e-22,2.020522e-22,5.767386e-18,NaN,0.011084,0.128079,0.046154,0.533333
33,1.00,4.00,1.000000,4.700096e-27,5.658524e-22,4.616616e-22,1.343606e-17,NaN,0.008790,0.128079,0.036601,0.533333
34,2.00,4.00,1.000000,1.258681e-27,1.434723e-22,1.159042e-22,3.406628e-18,NaN,0.007609,0.128079,0.031683,0.533333
35,4.00,4.00,1.000000,1.771574e-27,2.037233e-22,1.637630e-22,4.837228e-18,NaN,0.007009,0.128079,0.029187,0.533333